### ISSUE TITLE
how to model testing?

### ISSUE THREAD

**Issue by choiseonb1n** [KumapowerLIU/PD-GAN#11]
Using pre-learned data, we learned custom data through train.py and saved two types of .pth files.
How should I proceed with the test?

Total number of parameters: 186007263
2023-06-09 13:35:00.785 | INFO     | models.PDGAN:__init__:82 - ---------- Networks initialized Done-------------
2023-06-09 13:35:00.785 | INFO     | models.PDGAN:__init__:86 - Loading pre-trained network PDGAN! You choose the results of 120 epoch
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    model = create_model(cfg)
  File "/home/epozen/PD-GAN/models/models.py", line 13, in create_model
    model = PDGAN(cfg)
  File "/home/epozen/PD-GAN/models/PDGAN.py", line 89, in __init__
    self.load_networks(cfg.which_epoch)
  File "/home/epozen/PD-GAN/models/base_model.py", line 84, in load_networks
    print(getattr(self, "optimizer_" + name))
AttributeError: 'PDGAN' object has no attribute 'optimizer_PDGAN'

The following error occurs when proceeding with the [python test.py] command.

**Comment by DouglasQ** [comment]
I have the same problem now. Have you solved it ?

**Comment by ppppppppyyyy** [comment]
> I have the same problem now. Have you solved it ?

I have the same problem now. Have you solved it ?

**Comment by p6trick** [comment]
me too

**Comment by fittiing** [comment]
Have you solved this problem? Can you share how to test it?

**Comment by yooqoo** [comment]
Have you solved this problem?

**Comment by dabusidexiaoqiang111** [comment]
> Have you solved this problem?

**Comment by Jianzy-0730** [comment]
Have you solved this problem?

**Comment by andrewyu90** [comment]
There is no need for an optimiser, so just delete the line and all lines related to the optimiser. However, even though you have solved this issue, there is another issue that arises: the network dimensionality in the test step is not compatible with the training code.
